export const SEARCH_QUESTIONS = 'SEARCH_QUSTIONS';
export const SEARCH_QUESTIONS_SUCCESS = 'SEARCH_QUESTIONS_SUCCESS';
export const SEARCH_QUESTIONS_FAIL = 'SEARCH_QUESTIONS_FAIL';

export const SET_SORT = 'SET_SORT';
